sudo: false

os:
 - linux
 - osx

language: d

before_script: cd demos/new

d:
 - dmd-2.068.2
 - dmd-2.067.1

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub build --arch=$ARCH
